arkivo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^arkivo_app/', include('arkivo_app.urls')),
    url(r'^$', RedirectView.as_view(url='/arkivo_app/', permanent=True)),
]

arkivo_app/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'arkivo_app'
urlpatterns = [
    url(r'^settings/projects/add/', views.CompanyProjectsAddList, name='company_projects_add'),
    url(r'^settings/projects/edit/', views.CompanyProjectsEditList, name='company_projects_edit'),
    url(r'^settings/projects/', views.CompanyProjectsShowList, name='company_projects'),
    url(r'^settings/users/add/', views.CompanyUsersShowList, name='company_users_add'),
    url(r'^settings/users/edit/', views.CompanyUsersShowList, name='company_users_edit'),
    url(r'^settings/users/', views.CompanyUsersShowList, name='company_users'),
    url(r'^settings/systems/add/', views.CompanySystemsAddList, name='company_systems_add'),
    url(r'^settings/systems/edit/', views.CompanySystemsEditList, name='company_systems_edit'),
    url(r'^settings/systems/', views.CompanySystemsShowList, name='company_systems'),
    url(r'^settings/edit/', views.CompanyEditDetail, name='company_edit'),
    url(r'^settings/', views.CompanyShowDetail, name='company'),
    url(r'^(?P<project_name>[^/]+)/survey/$',views.SurveyShow, name = 'survey'),
    url(r'^(?P<project_name>[^/]+)/survey/(?P<section_name>[^/]+)/$', views.SurveyShow, name= 'survey_sec'),
    url(r'^(?P<project_name>.+)/survey/(?P<section_name>[^/].+)/(?P<category_name>[^/].+)/$', views.SurveyShow, name= 'survey_sec_cat'),
    url(r'^$', views.index, name='index'),
]


urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]


arkivo_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from django.utils.safestring import mark_safe
import uuid

# Create the form class.
class MyModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class CompanyForm(MyModelForm):
    class Meta:
        model = Company
        exclude = Company.hidden_fields



arkivo_app/views.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect,render_to_response,redirect
from django.http import HttpResponse
from django.template import loader

from django.contrib.auth.models import User
from django.core import serializers
from django.template.context_processors import csrf
from django.template import RequestContext  # For CSRF
from django.forms.formsets import formset_factory, BaseFormSet
from django.forms import modelformset_factory, BaseModelFormSet, inlineformset_factory
from django.views.generic import ListView,CreateView,UpdateView

from .models import *
from .forms import *
from .tables import *

@login_required
def index(request):
    current_user = request.user
    company = current_user.userprofile.get_active_company
    return render(request, 'arkivo_app/index.html',{
        'title': "Frontpage",
        'nav_url': 'index',
        'company': company,
    })

@login_required
def CompanyShowDetail(request, edit=False):
    current_user = request.user
    company = current_user.userprofile.get_active_company()
    display_static = True
    updated = False

    # check if edit is allowed
    allow_edit = True

    arg = request.build_absolute_uri()

    if allow_edit and edit:
        display_static= False

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CompanyForm(request.POST,instance=company)

        # check whether it's valid:
        if form.is_valid():
            display_static = True
            if form.has_changed():
                form.save()
                updated = True


    # if a GET (or any other method) we'll create a blank form
    else:
        form = CompanyForm(instance=company)

    return render(request, 'arkivo_app/company/detail.html', {
        'nav_url': 'arkivo_app:company',
        'company': company,
        'form': form,
        'display_static': display_static,
        'allow_edit': allow_edit,
        'updated': updated,
        'arg': arg,
    })

@login_required
def CompanyEditDetail(request):
    return CompanyShowDetail(request, edit=True)

@login_required
def CompanySystemsShowList(request, edit=False, extra=0):
    current_user = request.user
    company = current_user.userprofile.get_active_company()

    display_static = True
    updated = False

    # check if edit is allowed
    allow_edit = False
    if current_user.has_perm('arkivo_app.change_companysystem'):
        allow_edit = True

    if allow_edit and edit:
        display_static = False

    systems = CompanySystem.objects.filter(company = company)
    CompanySystemFormSet = modelformset_factory(CompanySystem,exclude=('id','company'),can_delete=True,extra=extra)
    if request.method == 'POST':
        formset = CompanySystemFormSet(
            request.POST,request.FILES,
            queryset=CompanySystem.objects.filter(company = company))
        if formset.is_valid() and formset.has_changed():
            for form in formset:
                form.instance.company = company
            formset.save()
            updated = True
            display_static = True
    else:
        formset = CompanySystemFormSet(queryset=CompanySystem.objects.filter(company=company))

    table = CompanySystemTable(systems)

    return render(request, 'arkivo_app/company/systems.html',{
        'nav_url': 'arkivo_app:company_systems',
        'formset': formset,
        'company': company,
        'systems': systems,
        'display_static': display_static,
        'allow_edit': allow_edit,
        'updated': updated,
        'table': table
    })

@login_required
def CompanySystemsEditList(request):
    request.session['add_count'] = 0
    return CompanySystemsShowList(request,edit=True)

@login_required
def CompanySystemsAddList(request):
    extra_count = request.session.get('add_count', 0)+1
    request.session['add_count'] = extra_count
    return CompanySystemsShowList(request,edit=True, extra=extra_count)


@login_required
def CompanyProjectsShowList(request, edit=False, extra=0):
    current_user = request.user
    company = current_user.userprofile.get_active_company()

    display_static = True
    updated = False

    # check if edit is allowed
    allow_edit = False
    if current_user.has_perm('arkivo_app.change_project'):
        allow_edit = True

    if allow_edit and edit:
        display_static = False

    projects = Project.objects.filter(company = company)
    CompanyProjectFormSet = modelformset_factory(Project,exclude=('id','company'),can_delete=True,extra=extra)
    if request.method == 'POST':
        formset = CompanyProjectFormSet(
            request.POST,request.FILES,
            queryset=Project.objects.filter(company = company))
        if formset.is_valid():
            display_static = True
            if formset.has_changed():
                for form in formset:
                    form.instance.company = company
                formset.save()
                updated = True


    else:
        formset = CompanyProjectFormSet(queryset=Project.objects.filter(company=company))

    table = CompanyProjectTable(projects)

    return render(request, 'arkivo_app/company/projects.html',{
        'nav_url': 'arkivo_app:company_projects',
        'formset': formset,
        'company': company,
        'projects': projects,
        'display_static': display_static,
        'allow_edit': allow_edit,
        'updated': updated,
        'table': table
    })

@login_required
def CompanyProjectsEditList(request):
    request.session['add_count'] = 0
    return CompanyProjectsShowList(request,edit=True)


@login_required
def CompanyProjectsAddList(request):
    extra_count = request.session.get('add_count', 0)+1
    request.session['add_count'] = extra_count
    return CompanyProjectsShowList(request,edit=True, extra=extra_count)


@login_required
def CompanyUsersShowList(request, edit=False, extra=0):
    current_user = request.user
    company = current_user.userprofile.get_active_company()

    display_static = True
    updated = False

    # make session counter on extra (if user presses many times on add button)

    # check if edit is allowed
    allow_edit = False

    if allow_edit and edit:
        display_static = False

    users = UserCompany.get_company_users(company_id=company.pk)
    UserFormSet = modelformset_factory(UserProfile, exclude=('id', 'company'), can_delete=True, extra=extra)
    if request.method == 'POST':
        formset = UserFormSet(
            request.POST, request.FILES,
            queryset=users)
        if formset.is_valid() and formset.has_changed():
            for form in formset:
                form.instance.company = company
            formset.save()
            updated = True
            display_static = True
    else:
        formset = UserFormSet(queryset=users)

    table = CompanyUserTable(users)

    return render(request, 'arkivo_app/company/users.html', {
        'nav_url': 'arkivo_app:company_users',
        'company': company,
        'formset': formset,
        'users': users,
        'display_static': display_static,
        'allow_edit': allow_edit,
        'updated': updated,
        'table': table
    })


@login_required
def SurveyShow(request, project_name, section_name='', category_name= ''):
    current_user = request.user
    company = current_user.userprofile.get_active_company()
    project = Project.objects.get(company = company, name = project_name, active = True)
    if not project:
        redirect('arkivo_app:index');

    survey = Survey.objects.get(project = project)

    # Get section
    qs = SurveySection.objects.filter(survey_template=survey.survey_template, name = section_name)
    if not qs:
        qs = SurveySection.objects.filter(survey_template=survey.survey_template)

    section = qs.first()

    # Get current category
    qs = QuestionCategory.objects.filter(survey_template=survey.survey_template, survey_section=section, name =category_name)
    if not qs:
        qs = QuestionCategory.objects.filter(survey_template=survey.survey_template, survey_section=section)

    category = qs.first()

    return render(request, 'arkivo_app/survey/survey.html', {
        'nav_url': 'arkivo_app:company_users',
        'company': company,
        'project': project,
        'survey':  survey,
        'section': section,
        'category': category,
        'section_name': section_name,
    })


arkivo_app/templates/arkivo_app/base.html
{% extends 'main_base.html' %}
{% load staticfiles %}

{% block body_type %} class="fixed-nav sticky-footer" id="page-top" {% endblock %}
{% block body_content %}

   <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="{% url 'arkivo_app:index' %}">
            <img src="{% static 'img/logo.png' %}" alt="logo" width="50%" style="width: 70%; display: inherit; margin-left: auto; margin-right: auto; margin-top: -10px; margin-bottom: -10px">
        </a>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            {% for project in company.get_active_projects %}
              <div class="arkivo-nav-group">
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <span class="navbar-text" >
                  Project: {{ project.name }}
                </span>
              </li>
              {% for survey in project.get_surveys %}
                  <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="{% url 'arkivo_app:survey' project.name %}">
                      <span class="nav-text"><i class="fa fa-fw fa-commenting" aria-hidden="true"></i> {{ survey.name }}</span>
                    </a>
                  </li>
              {% endfor %}
              </div>
            {% endfor %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'arkivo_app:company' %}">
                    <span class="nav-text"><i class="fa fa-fw fa-cog"></i> Settings</span>
                </a>
            </li>
            <li class="nav-item" >
                <a class="nav-link" href="#">
                    <span class="nav-text"><i class="fa fa-fw fa-question-circle"></i> Help</span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>
        <ul  class="navbar-nav mr-auto">
          <li class="nav-item">
               <span class="navbar-text" >
                    {{ company.name }}
               </span>
          </li>
        </ul>
        <ul  class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if user.is_staff %}
                <a class="nav-link" href="{% url 'admin:index'  %}">
                    <i class="fa fa-th-large" ></i> Admin Site
                </a>
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
               <i class="fa fa-user" aria-hidden="true"></i> {{ user.get_full_name }}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
              {% if user.is_authenticated %}
                 <i class="fa fa-fw fa-sign-out"></i>Logout
              {% else %}
                  <i class="fa fa-fw fa-sign-in"></i>Login
              {% endif %}
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="content-wrapper">

      <div class="container-fluid">

         {% block content %}
         {% endblock %}

      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- /.content-wrapper -->

    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright &copy; Your Website 2017</small>
        </div>
      </div>
    </footer>


    <!-- Logout Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'arkivo_app:logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'arkivo_app:login' %}">Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

{% endblock %}

arkivo_app/templates/arkivo_app/form_snippet.html
{% if form %}
    <!-- Form Errors -->
    {% if form.errors %}
        <ul class="errors">
            {% for error in form.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <!-- Display Form -->
    {% if display_static %}
        <form class="form-horizontal">
            {% for field in mymodel.get_display_detail.fields %}
            <div class="form-group row">
                <label class="control-label col-sm-3">{{ field.label }}:</label>
                <div class="col-sm-9">
                    <p class="form-control-static"> {{ field.value }}</p>
                </div>
            </div>
            {% endfor %}
            <! -- From Status -->
            {% if updated %}
                <div class="alert alert-success" role="alert">
                    <strong>Update successful</strong>
                </div>
            {% endif %}
        </form>

        {% if allow_edit %}
            {% with nav_url|add:"_edit" as edit_url %}
            <a class="btn col-sm-1" href="{% url edit_url %}" >Edit</a>
            {% endwith %}
        {% endif %}
    {% else %}
        <form name="form" action="" method="post" class="form-horizontal">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
                <label class="control-label col-sm-3" for = {{ field.id_for_label }}>{{ field.label_tag }}{{ field.label_suffix }}</label>
                <div class="col-sm-5">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn col-sm-1">Submit</button>
        </form>
    {% endif %}

{% endif %}

arkivo_app/templates/arkivo_app/formset_snippet.html


{% if display_static %}
    {% load django_tables2 %}
    {% render_table table %}
     {% if allow_edit %}
        {% with nav_url|add:"_edit" as edit_url %}
        <a class="btn col-sm-1" href="{% url edit_url %}" >Edit</a>
        {% endwith %}
     {% endif %}
{% else %}
    <form name="form" action="" method="post" class="form-horizontal">
    {% csrf_token %}
    {{ formset.management_form }}
    <div class="table-responsive">
        <table class="table table-responsive table-hover"  cellspacing="0">
            {% for form in formset %}
                {% if forloop.first %}
                    <thead>
                    <tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                {% endif %}
                <tr>
                {% for field in form.visible_fields %}
                    <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                    </td>
                {% endfor %}
                </tr>
                {% if forloop.last %}
                    </tbody>
                {% endif %}
            {% endfor %}
        </table>
    </div>
    {% with nav_url|add:"_add" as edit_url %}
       <a class="btn col-sm-1" href="{% url edit_url %}" ><i class="fa fa-plus" aria-hidden="true"></i></a>
     {% endwith %}
    <button type="submit" class="btn col-sm-1">Submit</button>
 </form>
{% endif %}

arkivo_app/templates/arkivo_app/index.html
{% extends 'arkivo_app/base.html' %}

{% block page_title %}
    Title
{% endblock %}

{% block content %}
    helloasda
{% endblock %}

arkivo_app/templates/arkivo_app/page_base.html
{% extends 'arkivo_app/base.html' %}

{% block content %}
    <div class="arkivo-page">
        <div class="row">
            <div class="col-2 arkivo-page-sidebar ">
                <h1> {% block page_sidebar_title %} Title {% endblock %} </h1>
                <div class = "arkivo-page-sidebar-nav">
                    {% block page_sidebar_content %}
                        <ul class="nav flex-column ">
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'arkivo_app:company' 1 %}">Company Info</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                          </li>
                        </ul>
                    {% endblock %}
                </div>
            </div>
            <div class="col-10 arkivo-page-content">
                <div class="arkivo-page-content">
                    <h1> {% block page_title %} Title {% endblock %} </h1>
                    <div class="arkivo-page-content-inner">
                        {% block page_content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}